// <auto-generated />
namespace HBO.MobileWebsite.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDisplayname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDisplayname));
        
        string IMigrationMetadata.Id
        {
            get { return "201904091628099_AddDisplayname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
